services:
  frontend:
    build:
      context: ./frontend/quotation
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "4000:4000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/logs:/app/logs
    restart: unless-stopped