import { FileText, Clock, RefreshCw, CheckCircle, Award, Ban } from 'lucide-react';

// Pagination
export const PAGE_SIZE_OPTIONS = [10, 20, 50];
export const DEBOUNCE_MS = 350;
'pending'
// Status Config
export const STATUS_CONFIG = {
  pending: { bg: '#fef9c3', color: '#92400e', dot: '#f59e0b', label: 'Awaiting Ops Review' },
  pending_admin: { bg: '#fef9c3', color: '#92400e', dot: '#f59e0b', label: 'Pending' },
  ops_approved: { bg: '#dbeafe', color: '#1e40af', dot: '#3b82f6', label: 'Forwarded to Admin' },
  ops_rejected: { bg: '#fee2e2', color: '#991b1b', dot: '#ef4444', label: 'Returned by Ops' },
  approved: { bg: '#dcfce7', color: '#166534', dot: '#22c55e', label: 'Approved' },
  rejected: { bg: '#fce7f3', color: '#9d174d', dot: '#ec4899', label: 'Rejected by Admin' },
  awarded: { bg: '#d1fae5', color: '#065f46', dot: '#10b981', label: 'Awarded ✓' },
  not_awarded: { bg: '#f3f4f6', color: '#374151', dot: '#9ca3af', label: 'Not Awarded' },
  draft: { bg: '#f1f5f9', color: '#475569', dot: '#94a3b8', label: 'Draft' },
};

// Tab Config
export const TAB_KEYS = {
  all: { label: 'All', Icon: FileText, statusFilter: null },
  pending: { label: 'Pending', Icon: Clock, statusFilter:['pending', 'pending_admin'] },
  in_review: { label: 'In Review', Icon: RefreshCw, statusFilter: 'ops_approved' },
  approved: { label: 'Approved', Icon: CheckCircle, statusFilter: 'approved' },
  awarded: { label: 'Awarded', Icon: Award, statusFilter: 'awarded' },
  returned: { label: 'Returned', Icon: Ban, statusFilter: ['ops_rejected', 'rejected'] },
};

export const DELETABLE = new Set(['pending', 'ops_rejected']);

// Currency
export const CURRENCY_SYMBOLS = {
  AED: 'د.إ', SAR: '﷼', QAR: '﷼', KWD: 'د.ك',
  BHD: '.د.ب', OMR: '﷼', USD: '$', EUR: '€', GBP: '£'
};

// File Upload
export const MAX_IMAGE_SIZE_MB = 5;
export const MAX_IMAGES_PER_ITEM = 6;
export const MAX_DOCUMENT_SIZE_MB = 10;

export const ALLOWED_IMAGE_TYPES = ['image/jpeg', 'image/png', 'image/webp', 'image/gif'];

export const ALLOWED_DOCUMENT_TYPES = [
  'image/jpeg', 'image/png', 'image/gif', 'image/webp',
  'application/pdf', 'application/msword',
  'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
  'application/vnd.ms-excel',
  'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
  'text/plain', 'application/zip', 'application/x-zip-compressed'
];

// Tax Presets
export const TAX_PRESETS = [
  { label: '0% VAT', value: 0, region: '' },
  { label: '5% VAT (UAE)', value: 5, region: 'UAE' },
  { label: '15% VAT (Saudi Arabia)', value: 15, region: 'Saudi Arabia' },
  { label: 'Manual (Enter custom %)', value: 'custom', region: '' },
];

export const DEFAULT_COMPANY_NAME = "Megarme General Contracting Co LLC";
export const DEFAULT_CURRENCY = 'AED';

// Snackbar
export const SNACK_HIDE = { show: false, message: "", type: "error" };
export const SNACK_ERROR = (msg) => ({ show: true, message: msg, type: "error" });
export const SNACK_SUCCESS = (msg) => ({ show: true, message: msg, type: "success" });

// Validation Messages
export const VALIDATION_MESSAGES = {
  REQUIRED_DATE: "Creation date is required.",
  REQUIRED_EXPIRY: "Expiry date is required.",
  EXPIRY_BEFORE_DATE: "Expiry date cannot be before the creation date.",
  TAX_RANGE: "VAT must be between 0 and 100.",
  TAX_REQUIRED: "VAT is required.",
  TAX_NUMBER: "VAT must be a number.",
  DISCOUNT_RANGE: "Discount must be between 0 and 100.",
  DISCOUNT_NUMBER: "Discount must be a number.",
  REQUIRED_ITEM: "Please add at least one item.",
  REQUIRED_ITEM_SELECT: "Please select an item for all rows."
};

// CSS Classes
export const CSS_CLASSES = {
  EDIT_INPUT: 'edit-input',
  FIELD_ERROR_INPUT: 'field-error-input',
  NO_PRINT: 'no-print',
  QUOTATION_CONTENT: 'quotation-content'
};

export const QUOTATION_NUMBER_FORMAT = 'QT-{yy}{mm}{dd}-{rn}';
export const BASE_URL = "";
export const ITEMS_PER_FIRST_PAGE = 8;

export const COUNTRY_CODES = [
  { code: '+93', country: 'Afghanistan', flag: '🇦🇫', name: 'Afghanistan' },
  { code: '+358', country: 'Aland Islands', flag: '🇦🇽', name: 'Aland Islands' },
  { code: '+355', country: 'Albania', flag: '🇦🇱', name: 'Albania' },
  { code: '+213', country: 'Algeria', flag: '🇩🇿', name: 'Algeria' },
  { code: '+1', country: 'American Samoa', flag: '🇦🇸', name: 'American Samoa' },
  { code: '+376', country: 'Andorra', flag: '🇦🇩', name: 'Andorra' },
  { code: '+244', country: 'Angola', flag: '🇦🇴', name: 'Angola' },
  { code: '+1', country: 'Anguilla', flag: '🇦🇮', name: 'Anguilla' },
  { code: '+672', country: 'Antarctica', flag: '🇦🇶', name: 'Antarctica' },
  { code: '+1', country: 'Antigua and Barbuda', flag: '🇦🇬', name: 'Antigua and Barbuda' },
  { code: '+54', country: 'Argentina', flag: '🇦🇷', name: 'Argentina' },
  { code: '+374', country: 'Armenia', flag: '🇦🇲', name: 'Armenia' },
  { code: '+297', country: 'Aruba', flag: '🇦🇼', name: 'Aruba' },
  { code: '+61', country: 'Ashmore and Cartier Islands', flag: '🇦🇺', name: 'Ashmore and Cartier Islands' },
  { code: '+61', country: 'Australia', flag: '🇦🇺', name: 'Australia' },
  { code: '+43', country: 'Austria', flag: '🇦🇹', name: 'Austria' },
  { code: '+994', country: 'Azerbaijan', flag: '🇦🇿', name: 'Azerbaijan' },
  { code: '+1', country: 'Bahamas', flag: '🇧🇸', name: 'Bahamas' },
  { code: '+973', country: 'Bahrain', flag: '🇧🇭', name: 'Bahrain' },
  { code: '+880', country: 'Bangladesh', flag: '🇧🇩', name: 'Bangladesh' },
  { code: '+1', country: 'Barbados', flag: '🇧🇧', name: 'Barbados' },
  { code: '+375', country: 'Belarus', flag: '🇧🇾', name: 'Belarus' },
  { code: '+32', country: 'Belgium', flag: '🇧🇪', name: 'Belgium' },
  { code: '+501', country: 'Belize', flag: '🇧🇿', name: 'Belize' },
  { code: '+229', country: 'Benin', flag: '🇧🇯', name: 'Benin' },
  { code: '+1', country: 'Bermuda', flag: '🇧🇲', name: 'Bermuda' },
  { code: '+975', country: 'Bhutan', flag: '🇧🇹', name: 'Bhutan' },
  { code: '+591', country: 'Bolivia', flag: '🇧🇴', name: 'Bolivia' },
  { code: '+599', country: 'Bonaire, Sint Eustatius and Saba', flag: '🇧🇶', name: 'Bonaire, Sint Eustatius and Saba' },
  { code: '+387', country: 'Bosnia', flag: '🇧🇦', name: 'Bosnia' },
  { code: '+387', country: 'Bosnia and Herzegovina', flag: '🇧🇦', name: 'Bosnia and Herzegovina' },
  { code: '+267', country: 'Botswana', flag: '🇧🇼', name: 'Botswana' },
  { code: '+47', country: 'Bouvet Island', flag: '🇧🇻', name: 'Bouvet Island' },
  { code: '+55', country: 'Brazil', flag: '🇧🇷', name: 'Brazil' },
  { code: '+246', country: 'British Indian Ocean Territory', flag: '🇮🇴', name: 'British Indian Ocean Territory' },
  { code: '+1', country: 'British Virgin Islands', flag: '🇻🇬', name: 'British Virgin Islands' },
  { code: '+673', country: 'Brunei', flag: '🇧🇳', name: 'Brunei' },
  { code: '+359', country: 'Bulgaria', flag: '🇧🇬', name: 'Bulgaria' },
  { code: '+226', country: 'Burkina Faso', flag: '🇧🇫', name: 'Burkina Faso' },
  { code: '+257', country: 'Burundi', flag: '🇧🇮', name: 'Burundi' },
  { code: '+855', country: 'Cambodia', flag: '🇰🇭', name: 'Cambodia' },
  { code: '+237', country: 'Cameroon', flag: '🇨🇲', name: 'Cameroon' },
  { code: '+1', country: 'Canada', flag: '🇨🇦', name: 'Canada' },
  { code: '+238', country: 'Cape Verde', flag: '🇨🇻', name: 'Cape Verde' },
  { code: '+1', country: 'Cayman Islands', flag: '🇰🇾', name: 'Cayman Islands' },
  { code: '+236', country: 'Central African Republic', flag: '🇨🇫', name: 'Central African Republic' },
  { code: '+235', country: 'Chad', flag: '🇹🇩', name: 'Chad' },
  { code: '+56', country: 'Chile', flag: '🇨🇱', name: 'Chile' },
  { code: '+86', country: 'China', flag: '🇨🇳', name: 'China' },
  { code: '+61', country: 'Christmas Island', flag: '🇨🇽', name: 'Christmas Island' },
  { code: '+33', country: 'Clipperton Island', flag: '🇨🇵', name: 'Clipperton Island' },
  { code: '+61', country: 'Cocos Islands', flag: '🇨🇨', name: 'Cocos Islands' },
  { code: '+57', country: 'Colombia', flag: '🇨🇴', name: 'Colombia' },
  { code: '+269', country: 'Comoros', flag: '🇰🇲', name: 'Comoros' },
  { code: '+242', country: 'Congo', flag: '🇨🇬', name: 'Congo' },
  { code: '+682', country: 'Cook Islands', flag: '🇨🇰', name: 'Cook Islands' },
  { code: '+61', country: 'Coral Sea Islands', flag: '🇦🇺', name: 'Coral Sea Islands' },
  { code: '+506', country: 'Costa Rica', flag: '🇨🇷', name: 'Costa Rica' },
  { code: '+385', country: 'Croatia', flag: '🇭🇷', name: 'Croatia' },
  { code: '+53', country: 'Cuba', flag: '🇨🇺', name: 'Cuba' },
  { code: '+599', country: 'Curacao', flag: '🇨🇼', name: 'Curacao' },
  { code: '+357', country: 'Cyprus', flag: '🇨🇾', name: 'Cyprus' },
  { code: '+420', country: 'Czech Republic', flag: '🇨🇿', name: 'Czech Republic' },
  { code: '+243', country: 'DR Congo', flag: '🇨🇩', name: 'DR Congo' },
  { code: '+45', country: 'Denmark', flag: '🇩🇰', name: 'Denmark' },
  { code: '+253', country: 'Djibouti', flag: '🇩🇯', name: 'Djibouti' },
  { code: '+1', country: 'Dominica', flag: '🇩🇲', name: 'Dominica' },
  { code: '+1', country: 'Dominican Republic', flag: '🇩🇴', name: 'Dominican Republic' },
  { code: '+593', country: 'Ecuador', flag: '🇪🇨', name: 'Ecuador' },
  { code: '+20', country: 'Egypt', flag: '🇪🇬', name: 'Egypt' },
  { code: '+503', country: 'El Salvador', flag: '🇸🇻', name: 'El Salvador' },
  { code: '+240', country: 'Equatorial Guinea', flag: '🇬🇶', name: 'Equatorial Guinea' },
  { code: '+291', country: 'Eritrea', flag: '🇪🇷', name: 'Eritrea' },
  { code: '+372', country: 'Estonia', flag: '🇪🇪', name: 'Estonia' },
  { code: '+268', country: 'Eswatini', flag: '🇸🇿', name: 'Eswatini' },
  { code: '+251', country: 'Ethiopia', flag: '🇪🇹', name: 'Ethiopia' },
  { code: '+500', country: 'Falkland Islands', flag: '🇫🇰', name: 'Falkland Islands' },
  { code: '+298', country: 'Faroe Islands', flag: '🇫🇴', name: 'Faroe Islands' },
  { code: '+679', country: 'Fiji', flag: '🇫🇯', name: 'Fiji' },
  { code: '+358', country: 'Finland', flag: '🇫🇮', name: 'Finland' },
  { code: '+33', country: 'France', flag: '🇫🇷', name: 'France' },
  { code: '+594', country: 'French Guiana', flag: '🇬🇫', name: 'French Guiana' },
  { code: '+689', country: 'French Polynesia', flag: '🇵🇫', name: 'French Polynesia' },
  { code: '+262', country: 'French Southern Territories', flag: '🇹🇫', name: 'French Southern Territories' },
  { code: '+241', country: 'Gabon', flag: '🇬🇦', name: 'Gabon' },
  { code: '+220', country: 'Gambia', flag: '🇬🇲', name: 'Gambia' },
  { code: '+995', country: 'Georgia', flag: '🇬🇪', name: 'Georgia' },
  { code: '+49', country: 'Germany', flag: '🇩🇪', name: 'Germany' },
  { code: '+233', country: 'Ghana', flag: '🇬🇭', name: 'Ghana' },
  { code: '+350', country: 'Gibraltar', flag: '🇬🇮', name: 'Gibraltar' },
  { code: '+30', country: 'Greece', flag: '🇬🇷', name: 'Greece' },
  { code: '+299', country: 'Greenland', flag: '🇬🇱', name: 'Greenland' },
  { code: '+1', country: 'Grenada', flag: '🇬🇩', name: 'Grenada' },
  { code: '+590', country: 'Guadeloupe', flag: '🇬🇵', name: 'Guadeloupe' },
  { code: '+1', country: 'Guam', flag: '🇬🇺', name: 'Guam' },
  { code: '+502', country: 'Guatemala', flag: '🇬🇹', name: 'Guatemala' },
  { code: '+44', country: 'Guernsey', flag: '🇬🇬', name: 'Guernsey' },
  { code: '+224', country: 'Guinea', flag: '🇬🇳', name: 'Guinea' },
  { code: '+245', country: 'Guinea-Bissau', flag: '🇬🇼', name: 'Guinea-Bissau' },
  { code: '+592', country: 'Guyana', flag: '🇬🇾', name: 'Guyana' },
  { code: '+509', country: 'Haiti', flag: '🇭🇹', name: 'Haiti' },
  { code: '+672', country: 'Heard Island and McDonald Islands', flag: '🇭🇲', name: 'Heard Island and McDonald Islands' },
  { code: '+503', country: 'High Seas', flag: '🌊', name: 'High Seas' },
  { code: '+504', country: 'Honduras', flag: '🇭🇳', name: 'Honduras' },
  { code: '+852', country: 'Hong Kong', flag: '🇭🇰', name: 'Hong Kong' },
  { code: '+36', country: 'Hungary', flag: '🇭🇺', name: 'Hungary' },
  { code: '+354', country: 'Iceland', flag: '🇮🇸', name: 'Iceland' },
  { code: '+91', country: 'India', flag: '🇮🇳', name: 'India' },
  { code: '+62', country: 'Indonesia', flag: '🇮🇩', name: 'Indonesia' },
  { code: '+98', country: 'Iran', flag: '🇮🇷', name: 'Iran' },
  { code: '+964', country: 'Iraq', flag: '🇮🇶', name: 'Iraq' },
  { code: '+353', country: 'Ireland', flag: '🇮🇪', name: 'Ireland' },
  { code: '+44', country: 'Isle of Man', flag: '🇮🇲', name: 'Isle of Man' },
  { code: '+972', country: 'Israel', flag: '🇮🇱', name: 'Israel' },
  { code: '+39', country: 'Italy', flag: '🇮🇹', name: 'Italy' },
  { code: '+225', country: "Côte d'Ivoire", flag: '🇨🇮', name: "Côte d'Ivoire" },
  { code: '+1', country: 'Jamaica', flag: '🇯🇲', name: 'Jamaica' },
  { code: '+81', country: 'Japan', flag: '🇯🇵', name: 'Japan' },
  { code: '+44', country: 'Jersey', flag: '🇯🇪', name: 'Jersey' },
  { code: '+962', country: 'Jordan', flag: '🇯🇴', name: 'Jordan' },
  { code: '+7', country: 'Kazakhstan', flag: '🇰🇿', name: 'Kazakhstan' },
  { code: '+254', country: 'Kenya', flag: '🇰🇪', name: 'Kenya' },
  { code: '+686', country: 'Kiribati', flag: '🇰🇮', name: 'Kiribati' },
  { code: '+383', country: 'Kosova Republic', flag: '🇽🇰', name: 'Kosova Republic' },
  { code: '+383', country: 'Kosovo', flag: '🇽🇰', name: 'Kosovo' },
  { code: '+965', country: 'Kuwait', flag: '🇰🇼', name: 'Kuwait' },
  { code: '+996', country: 'Kyrgyzstan', flag: '🇰🇬', name: 'Kyrgyzstan' },
  { code: '+856', country: 'Laos', flag: '🇱🇦', name: 'Laos' },
  { code: '+371', country: 'Latvia', flag: '🇱🇻', name: 'Latvia' },
  { code: '+961', country: 'Lebanon', flag: '🇱🇧', name: 'Lebanon' },
  { code: '+266', country: 'Lesotho', flag: '🇱🇸', name: 'Lesotho' },
  { code: '+231', country: 'Liberia', flag: '🇱🇷', name: 'Liberia' },
  { code: '+218', country: 'Libya', flag: '🇱🇾', name: 'Libya' },
  { code: '+423', country: 'Liechtenstein', flag: '🇱🇮', name: 'Liechtenstein' },
  { code: '+370', country: 'Lithuania', flag: '🇱🇹', name: 'Lithuania' },
  { code: '+352', country: 'Luxembourg', flag: '🇱🇺', name: 'Luxembourg' },
  { code: '+853', country: 'Macau', flag: '🇲🇴', name: 'Macau' },
  { code: '+261', country: 'Madagascar', flag: '🇲🇬', name: 'Madagascar' },
  { code: '+265', country: 'Malawi', flag: '🇲🇼', name: 'Malawi' },
  { code: '+60', country: 'Malaysia', flag: '🇲🇾', name: 'Malaysia' },
  { code: '+960', country: 'Maldives', flag: '🇲🇻', name: 'Maldives' },
  { code: '+223', country: 'Mali', flag: '🇲🇱', name: 'Mali' },
  { code: '+356', country: 'Malta', flag: '🇲🇹', name: 'Malta' },
  { code: '+692', country: 'Marshall Islands', flag: '🇲🇭', name: 'Marshall Islands' },
  { code: '+596', country: 'Martinique', flag: '🇲🇶', name: 'Martinique' },
  { code: '+222', country: 'Mauritania', flag: '🇲🇷', name: 'Mauritania' },
  { code: '+230', country: 'Mauritius', flag: '🇲🇺', name: 'Mauritius' },
  { code: '+262', country: 'Mayotte', flag: '🇾🇹', name: 'Mayotte' },
  { code: '+52', country: 'Mexico', flag: '🇲🇽', name: 'Mexico' },
  { code: '+691', country: 'Micronesia', flag: '🇫🇲', name: 'Micronesia' },
  { code: '+373', country: 'Moldova', flag: '🇲🇩', name: 'Moldova' },
  { code: '+377', country: 'Monaco', flag: '🇲🇨', name: 'Monaco' },
  { code: '+976', country: 'Mongolia', flag: '🇲🇳', name: 'Mongolia' },
  { code: '+382', country: 'Montenegro', flag: '🇲🇪', name: 'Montenegro' },
  { code: '+1', country: 'Montserrat', flag: '🇲🇸', name: 'Montserrat' },
  { code: '+212', country: 'Morocco', flag: '🇲🇦', name: 'Morocco' },
  { code: '+258', country: 'Mozambique', flag: '🇲🇿', name: 'Mozambique' },
  { code: '+95', country: 'Myanmar', flag: '🇲🇲', name: 'Myanmar' },
  { code: '+264', country: 'Namibia', flag: '🇳🇦', name: 'Namibia' },
  { code: '+674', country: 'Nauru', flag: '🇳🇷', name: 'Nauru' },
  { code: '+977', country: 'Nepal', flag: '🇳🇵', name: 'Nepal' },
  { code: '+31', country: 'Netherlands', flag: '🇳🇱', name: 'Netherlands' },
  { code: '+599', country: 'Netherlands Antilles', flag: '🇧🇶', name: 'Netherlands Antilles' },
  { code: '+687', country: 'New Caledonia', flag: '🇳🇨', name: 'New Caledonia' },
  { code: '+64', country: 'New Zealand', flag: '🇳🇿', name: 'New Zealand' },
  { code: '+505', country: 'Nicaragua', flag: '🇳🇮', name: 'Nicaragua' },
  { code: '+227', country: 'Niger', flag: '🇳🇪', name: 'Niger' },
  { code: '+234', country: 'Nigeria', flag: '🇳🇬', name: 'Nigeria' },
  { code: '+683', country: 'Niue', flag: '🇳🇺', name: 'Niue' },
  { code: '+672', country: 'Norfolk Island', flag: '🇳🇫', name: 'Norfolk Island' },
  { code: '+850', country: 'North Korea', flag: '🇰🇵', name: 'North Korea' },
  { code: '+389', country: 'North Macedonia', flag: '🇲🇰', name: 'North Macedonia' },
  { code: '+1', country: 'Northern Mariana Islands', flag: '🇲🇵', name: 'Northern Mariana Islands' },
  { code: '+47', country: 'Norway', flag: '🇳🇴', name: 'Norway' },
  { code: '+968', country: 'Oman', flag: '🇴🇲', name: 'Oman' },
  { code: '+92', country: 'Pakistan', flag: '🇵🇰', name: 'Pakistan' },
  { code: '+680', country: 'Palau', flag: '🇵🇼', name: 'Palau' },
  { code: '+970', country: 'Palestine', flag: '🇵🇸', name: 'Palestine' },
  { code: '+507', country: 'Panama', flag: '🇵🇦', name: 'Panama' },
  { code: '+675', country: 'Papua New Guinea', flag: '🇵🇬', name: 'Papua New Guinea' },
  { code: '+595', country: 'Paraguay', flag: '🇵🇾', name: 'Paraguay' },
  { code: '+51', country: 'Peru', flag: '🇵🇪', name: 'Peru' },
  { code: '+63', country: 'Philippines', flag: '🇵🇭', name: 'Philippines' },
  { code: '+64', country: 'Pitcairn', flag: '🇵🇳', name: 'Pitcairn' },
  { code: '+48', country: 'Poland', flag: '🇵🇱', name: 'Poland' },
  { code: '+351', country: 'Portugal', flag: '🇵🇹', name: 'Portugal' },
  { code: '+1', country: 'Puerto Rico', flag: '🇵🇷', name: 'Puerto Rico' },
  { code: '+974', country: 'Qatar', flag: '🇶🇦', name: 'Qatar' },
  { code: '+262', country: 'Reunion', flag: '🇷🇪', name: 'Reunion' },
  { code: '+40', country: 'Romania', flag: '🇷🇴', name: 'Romania' },
  { code: '+7', country: 'Russia', flag: '🇷🇺', name: 'Russia' },
  { code: '+250', country: 'Rwanda', flag: '🇷🇼', name: 'Rwanda' },
  { code: '+590', country: 'Saint Barthelemy', flag: '🇧🇱', name: 'Saint Barthelemy' },
  { code: '+290', country: 'Saint Helena', flag: '🇸🇭', name: 'Saint Helena' },
  { code: '+1', country: 'Saint Kitts and Nevis', flag: '🇰🇳', name: 'Saint Kitts and Nevis' },
  { code: '+1', country: 'Saint Lucia', flag: '🇱🇨', name: 'Saint Lucia' },
  { code: '+590', country: 'Saint Martin', flag: '🇲🇫', name: 'Saint Martin' },
  { code: '+508', country: 'Saint Pierre and Miquelon', flag: '🇵🇲', name: 'Saint Pierre and Miquelon' },
  { code: '+1', country: 'Saint Vincent and the Grenadines', flag: '🇻🇨', name: 'Saint Vincent and the Grenadines' },
  { code: '+685', country: 'Samoa', flag: '🇼🇸', name: 'Samoa' },
  { code: '+378', country: 'San Marino', flag: '🇸🇲', name: 'San Marino' },
  { code: '+239', country: 'Sao Tome and Principe', flag: '🇸🇹', name: 'Sao Tome and Principe' },
  { code: '+966', country: 'Saudi Arabia', flag: '🇸🇦', name: 'Saudi Arabia' },
  { code: '+221', country: 'Senegal', flag: '🇸🇳', name: 'Senegal' },
  { code: '+381', country: 'Serbia', flag: '🇷🇸', name: 'Serbia' },
  { code: '+381', country: 'Serbia and Montenegro', flag: '🇷🇸', name: 'Serbia and Montenegro' },
  { code: '+248', country: 'Seychelles', flag: '🇸🇨', name: 'Seychelles' },
  { code: '+232', country: 'Sierra Leone', flag: '🇸🇱', name: 'Sierra Leone' },
  { code: '+65', country: 'Singapore', flag: '🇸🇬', name: 'Singapore' },
  { code: '+1', country: 'Sint Maarten', flag: '🇸🇽', name: 'Sint Maarten' },
  { code: '+421', country: 'Slovakia', flag: '🇸🇰', name: 'Slovakia' },
  { code: '+386', country: 'Slovenia', flag: '🇸🇮', name: 'Slovenia' },
  { code: '+677', country: 'Solomon Islands', flag: '🇸🇧', name: 'Solomon Islands' },
  { code: '+252', country: 'Somalia', flag: '🇸🇴', name: 'Somalia' },
  { code: '+252', country: 'Somaliland', flag: '🏴', name: 'Somaliland' },
  { code: '+27', country: 'South Africa', flag: '🇿🇦', name: 'South Africa' },
  { code: '+500', country: 'South Georgia and the South Sandwich Islands', flag: '🇬🇸', name: 'South Georgia and the South Sandwich Islands' },
  { code: '+82', country: 'South Korea', flag: '🇰🇷', name: 'South Korea' },
  { code: '+211', country: 'South Sudan', flag: '🇸🇸', name: 'South Sudan' },
  { code: '+34', country: 'Spain', flag: '🇪🇸', name: 'Spain' },
  { code: '+94', country: 'Sri Lanka', flag: '🇱🇰', name: 'Sri Lanka' },
  { code: '+249', country: 'Sudan', flag: '🇸🇩', name: 'Sudan' },
  { code: '+597', country: 'Suriname', flag: '🇸🇷', name: 'Suriname' },
  { code: '+47', country: 'Svalbard and Jan Mayen', flag: '🇸🇯', name: 'Svalbard and Jan Mayen' },
  { code: '+268', country: 'Swaziland', flag: '🇸🇿', name: 'Swaziland' },
  { code: '+46', country: 'Sweden', flag: '🇸🇪', name: 'Sweden' },
  { code: '+41', country: 'Switzerland', flag: '🇨🇭', name: 'Switzerland' },
  { code: '+963', country: 'Syria', flag: '🇸🇾', name: 'Syria' },
  { code: '+886', country: 'Taiwan', flag: '🇹🇼', name: 'Taiwan' },
  { code: '+992', country: 'Tajikistan', flag: '🇹🇯', name: 'Tajikistan' },
  { code: '+255', country: 'Tanzania', flag: '🇹🇿', name: 'Tanzania' },
  { code: '+66', country: 'Thailand', flag: '🇹🇭', name: 'Thailand' },
  { code: '+670', country: 'Timor Leste', flag: '🇹🇱', name: 'Timor Leste' },
  { code: '+228', country: 'Togo', flag: '🇹🇬', name: 'Togo' },
  { code: '+690', country: 'Tokelau', flag: '🇹🇰', name: 'Tokelau' },
  { code: '+676', country: 'Tonga', flag: '🇹🇴', name: 'Tonga' },
  { code: '+1', country: 'Trinidad and Tobago', flag: '🇹🇹', name: 'Trinidad and Tobago' },
  { code: '+216', country: 'Tunisia', flag: '🇹🇳', name: 'Tunisia' },
  { code: '+90', country: 'Turkey', flag: '🇹🇷', name: 'Turkey' },
  { code: '+993', country: 'Turkmenistan', flag: '🇹🇲', name: 'Turkmenistan' },
  { code: '+1', country: 'Turks and Caicos Islands', flag: '🇹🇨', name: 'Turks and Caicos Islands' },
  { code: '+688', country: 'Tuvalu', flag: '🇹🇻', name: 'Tuvalu' },
  { code: '+971', country: 'U.A.E', flag: '🇦🇪', name: 'U.A.E' },
  { code: '+1', country: 'U.S.A', flag: '🇺🇸', name: 'U.S.A' },
  { code: '+256', country: 'Uganda', flag: '🇺🇬', name: 'Uganda' },
  { code: '+380', country: 'Ukraine', flag: '🇺🇦', name: 'Ukraine' },
  { code: '+971', country: 'United Arab Emirates', flag: '🇦🇪', name: 'United Arab Emirates' },
  { code: '+44', country: 'United Kingdom', flag: '🇬🇧', name: 'United Kingdom' },
  { code: '+1', country: 'United States Minor Outlying Islands', flag: '🇺🇲', name: 'United States Minor Outlying Islands' },
  { code: '+598', country: 'Uruguay', flag: '🇺🇾', name: 'Uruguay' },
  { code: '+998', country: 'Uzbekistan', flag: '🇺🇿', name: 'Uzbekistan' },
  { code: '+678', country: 'Vanuatu', flag: '🇻🇺', name: 'Vanuatu' },
  { code: '+379', country: 'Vatican City', flag: '🇻🇦', name: 'Vatican City' },
  { code: '+58', country: 'Venezuela', flag: '🇻🇪', name: 'Venezuela' },
  { code: '+84', country: 'Vietnam', flag: '🇻🇳', name: 'Vietnam' },
  { code: '+1', country: 'Virgin Islands, British', flag: '🇻🇬', name: 'Virgin Islands, British' },
  { code: '+1', country: 'Virgin Islands, U.S.', flag: '🇻🇮', name: 'Virgin Islands, U.S.' },
  { code: '+681', country: 'Wallis and Futuna', flag: '🇼🇫', name: 'Wallis and Futuna' },
  { code: '+212', country: 'Western Sahara', flag: '🇪🇭', name: 'Western Sahara' },
  { code: '+967', country: 'Yemen', flag: '🇾🇪', name: 'Yemen' },
  { code: '+260', country: 'Zambia', flag: '🇿🇲', name: 'Zambia' },
  { code: '+263', country: 'Zimbabwe', flag: '🇿🇼', name: 'Zimbabwe' },
];